application: s~isthatawordadam
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /javascript
  static_dir: javascript

- url: .*
  script: main.app

builtins:
- remote_api: on

skip_files: |
    ^(.*/)?(
    (.*\.pyc)|
    (.*\.css.map)|
    (.*\.scss)|
    (.sass-cache/.*)|
    )$

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
